# Generated by Django 3.0.2 on 2021-02-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='userid',
            new_name='uid',
        ),
    ]
