# Generated by Django 3.0.2 on 2021-02-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210216_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userTable',
        ),
    ]
