# Generated by Django 3.0.2 on 2021-02-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('coordinates', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
