# Generated by Django 3.0.2 on 2021-02-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('primary_category', models.CharField(max_length=20)),
                ('secondary_category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('img_path', models.ImageField(upload_to='products/')),
                ('tags', models.CharField(max_length=20)),
                ('rating_count', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('offer', models.FloatField(default=0.0)),
            ],
        ),
    ]
