# Generated by Django 3.0.2 on 2021-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_types',
            field=models.CharField(choices=[('kgs', 'kgs'), ('peices', 'peices'), ('litre', 'litre')], default='kgs', max_length=10),
        ),
    ]
