# Generated by Django 3.0.2 on 2021-02-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210219_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('grand_total', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserTable')),
            ],
        ),
    ]
