# Generated by Django 3.0.2 on 2021-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adminuser_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='pwd',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='adm_pwd',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='pwd',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
