# Generated by Django 3.0.2 on 2021-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210221_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='adm_pwd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='pwd',
            field=models.CharField(max_length=50),
        ),
    ]
