# Generated by Django 3.1.7 on 2021-02-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210221_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=20)),
                ('primary_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.primarycategory')),
            ],
        ),
    ]
