from .usertb import UserTable
from .admin_user import AdminUser
from .delivery_user import DeliveryUser
from .delivery_histroy import DeliveryHistory
from .product import Product
from .cart import Cart
from .favourite import FavouriteProduct
from .order import Order
from .order_item import OrderItem
from .promo_code import PromoCode
from .promo_used import PromoUsed
from .primary_cat import PrimaryCategory
from .secondary_cat import SecondaryCategory
